[package]
name = "management_system_server"
version = "0.1.0"
authors = ["Hermes"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0"
log = "0.4.8"